# Setup
title:        Taehyun Kim
tagline:      Tech & Research
baseurl:      "https://taehyunkim1527.github.io/taehyunkim1527/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Taehyun Kim
  url:        https://taehyunkim1527.github.io/taehyunkim1527/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
